#!/bin/bash
#BEGIN LICENSE
#
# Copyright © Blue Mind SAS, 2012-2016
#
# This file is part of BlueMind. BlueMind is a messaging and collaborative
# solution.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of either the GNU Affero General Public License as
# published by the Free Software Foundation (version 3 of the License).
#
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# See LICENSE.txt


set -e

# Source debconf library.
. /usr/share/debconf/confmodule

is_initial_configuration() {
  # Check if this is the initial configuration and not an upgrade of an 
  # existing configuration 
  # Usage: if is_initial_configuration "$@"; then ... fi from top level 

  # Plain installation 
  if [ "$1" = configure ] && [ -z "$2" ]; then
    return 0
  fi

  # Configuration via dpkg-reconfigure 
  if [ "$1" = reconfigure ] || [ "$DEBCONF_RECONFIGURE" ]; then
    return 0
  fi

  return 1
}

for file in /etc/bm/nodeclient_cert.pem \
  /etc/bm/nodeclient_key.pem \
  /etc/bm/nodeclient.p12 \
  /etc/bm/nodeclient_keystore.jks \
  /etc/bm/nodeclient_truststore.jks \
  /etc/bm/bm.jks; do
    if [ -e ${file} ]; then
        chmod 400 ${file}
    fi
done

if [ -e /etc/bm/bm-core.tok ]; then
    chmod 440 /etc/bm/bm-core.tok
    chown root:www-data /etc/bm/bm-core.tok
fi

exit 0
