<?php

/*
 +-----------------------------------------------------------------------+
 | localization/es_ES/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Jorge López <jorge@adobo.org>                                |
 +-----------------------------------------------------------------------+
*/

$labels = array();
include INSTALL_PATH . "program/localization/es.php";
?>
