// messages
export const ADD_ATTACHMENTS = "ADD_ATTACHMENTS";
export const ADD_FLAG = "ADD_FLAG";
export const CREATE_MESSAGE = "CREATE_MESSAGE";
export const DELETE_FLAG = "DELETE_FLAG";
export const FETCH_MESSAGE_METADATA = "FETCH_MESSAGE_METADATA";
export const REMOVE_ATTACHMENT = "REMOVE_ATTACHMENT";
export const REMOVE_MESSAGES = "REMOVE_MESSAGES";
export const SAVE_MESSAGE = "SAVE_MESSAGE";
export const SEND_MESSAGE = "SEND_MESSAGE";

// messageList
export const FETCH_MESSAGE_LIST_KEYS = "FETCH_MESSAGE_LIST_KEYS";
export const REFRESH_MESSAGE_LIST_KEYS = "REFRESH_MESSAGE_LIST_KEYS";
