// mailboxes

export const FETCH_MAILBOXES = "FETCH_MAILBOXES";

// folders

export const FETCH_FOLDERS = "FETCH_FOLDERS";
export const CREATE_FOLDER = "CREATE_FOLDER";
export const CREATE_FOLDER_HIERARCHY = "CREATE_FOLDER_HIERARCHY";
export const REMOVE_FOLDER = "REMOVE_FOLDER";
export const RENAME_FOLDER = "RENAME_FOLDER";
export const MARK_FOLDER_AS_READ = "MARK_FOLDER_AS_READ";

// messages
export const ADD_ATTACHMENTS = "ADD_ATTACHMENTS";
export const ADD_FLAG = "ADD_FLAG";
export const DELETE_FLAG = "DELETE_FLAG";
export const FETCH_MESSAGE_METADATA = "FETCH_MESSAGE_METADATA";
export const MARK_MESSAGE_AS_FLAGGED = "MARK_MESSAGE_AS_FLAGGED";
export const MARK_MESSAGE_AS_READ = "MARK_MESSAGE_AS_READ";
export const MARK_MESSAGE_AS_UNFLAGGED = "MARK_MESSAGE_AS_UNFLAGGED";
export const MARK_MESSAGE_AS_UNREAD = "MARK_MESSAGE_AS_UNREAD";
export const MARK_MESSAGES_AS_FLAGGED = "MARK_MESSAGES_AS_FLAGGED";
export const MARK_MESSAGES_AS_READ = "MARK_MESSAGES_AS_READ";
export const MARK_MESSAGES_AS_UNFLAGGED = "MARK_MESSAGES_AS_UNFLAGGED";
export const MARK_MESSAGES_AS_UNREAD = "MARK_MESSAGES_AS_UNREAD";
export const MOVE_MESSAGES = "MOVE_MESSAGES";
export const MOVE_MESSAGES_TO_TRASH = "MOVE_MESSAGES_TO_TRASH";
export const REMOVE_ATTACHMENT = "REMOVE_ATTACHMENT";
export const REMOVE_MESSAGES = "REMOVE_MESSAGES";
export const SAVE_MESSAGE = "SAVE_MESSAGE";
export const SEND_MESSAGE = "SEND_MESSAGE";

// messageList
export const FETCH_MESSAGE_LIST_KEYS = "FETCH_MESSAGE_LIST_KEYS";
export const REFRESH_MESSAGE_LIST_KEYS = "REFRESH_MESSAGE_LIST_KEYS";

// messageCompose
export const FETCH_SIGNATURE = "FETCH_SIGNATURE";

// consultPanel
export const FETCH_EVENT = "FETCH_EVENT";
export const SET_EVENT_STATUS = "SET_EVENT_STATUS";
export const ACCEPT_COUNTER_EVENT = "ACCEPT_COUNTER_EVENT";
export const DECLINE_COUNTER_EVENT = "DECLINE_COUNTER_EVENT";
