// partsData
export const COMPUTE_QUOTE_NODES = "COMPUTE_QUOTE_NODES";
export const FETCH_PART_DATA = "FETCH_PART_DATA";

// mailboxes
export const FETCH_MAILBOXES = "FETCH_MAILBOXES";

// folders
export const CREATE_FOLDER = "CREATE_FOLDER";
export const CREATE_FOLDER_HIERARCHY = "CREATE_FOLDER_HIERARCHY";
export const EMPTY_FOLDER = "EMPTY_FOLDER";
export const EMPTY_TRASH = "EMPTY_TRASH";
export const FETCH_FOLDERS = "FETCH_FOLDERS";
export const MARK_FOLDER_AS_READ = "MARK_FOLDER_AS_READ";
export const MOVE_FOLDER = "MOVE_FOLDER";
export const REMOVE_FOLDER = "REMOVE_FOLDER";
export const RENAME_FOLDER = "RENAME_FOLDER";
export const UNREAD_FOLDER_COUNT = "$_VueBus_mail-webapp_unread_folder_count";
export const PUSHED_FOLDER_CHANGES = "$_VueBus_mail-webapp_pushed_folder_changes";

// messages
export const ADD_ATTACHMENTS = "ADD_ATTACHMENTS";
export const ADD_FLAG = "ADD_FLAG";
export const DEBOUNCED_SAVE_MESSAGE = "DEBOUNCED_SAVE_MESSAGE";
export const DELETE_FLAG = "DELETE_FLAG";
export const FETCH_MESSAGE_IF_NOT_LOADED = "FETCH_MESSAGE_IF_NOT_LOADED";
export const FETCH_MESSAGE_METADATA = "FETCH_MESSAGE_METADATA";
export const MARK_MESSAGE_AS_FLAGGED = "MARK_MESSAGE_AS_FLAGGED";
export const MARK_MESSAGE_AS_READ = "MARK_MESSAGE_AS_READ";
export const MARK_MESSAGE_AS_UNFLAGGED = "MARK_MESSAGE_AS_UNFLAGGED";
export const MARK_MESSAGE_AS_UNREAD = "MARK_MESSAGE_AS_UNREAD";
export const MARK_MESSAGES_AS_FLAGGED = "MARK_MESSAGES_AS_FLAGGED";
export const MARK_MESSAGES_AS_READ = "MARK_MESSAGES_AS_READ";
export const MARK_MESSAGES_AS_UNFLAGGED = "MARK_MESSAGES_AS_UNFLAGGED";
export const MARK_MESSAGES_AS_UNREAD = "MARK_MESSAGES_AS_UNREAD";
export const MOVE_MESSAGES = "MOVE_MESSAGES";
export const REMOVE_ATTACHMENT = "REMOVE_ATTACHMENT";
export const REMOVE_MESSAGES = "REMOVE_MESSAGES";
export const SAVE_MESSAGE = "SAVE_MESSAGE";
export const SAVE_AS_DRAFT = "SAVE_AS_DRAFT";
export const SAVE_AS_TEMPLATE = "SAVE_AS_TEMPLATE";
export const SEND_MESSAGE = "SEND_MESSAGE";

// conversationList
export const FETCH_CONVERSATION_LIST_KEYS = "FETCH_CONVERSATION_LIST_KEYS";
export const CONVERSATION_LIST_NEXT_PAGE = "CONVERSATION_LIST_NEXT_PAGE";
export const REFRESH_CONVERSATION_LIST_KEYS = "REFRESH_CONVERSATION_LIST_KEYS";

// messageCompose
export const CHECK_CORPORATE_SIGNATURE = "CHECK_CORPORATE_SIGNATURE";
export const FETCH_TEMPLATES_KEYS = "FETCH_TEMPLATES_KEYS";
export const LOAD_MAX_MESSAGE_SIZE = "LOAD_MAX_MESSAGE_SIZE";

// consultPanel
export const FETCH_EVENT = "FETCH_EVENT";
export const SET_EVENT_STATUS = "SET_EVENT_STATUS";
export const ACCEPT_COUNTER_EVENT = "ACCEPT_COUNTER_EVENT";
export const DECLINE_COUNTER_EVENT = "DECLINE_COUNTER_EVENT";

// conversations
export const FETCH_CONVERSATION_IF_NOT_LOADED = "FETCH_CONVERSATION_IF_NOT_LOADED";
export const FETCH_CONVERSATIONS = "FETCH_CONVERSATIONS";
export const MARK_CONVERSATIONS_AS_FLAGGED = "MARK_CONVERSATIONS_AS_FLAGGED";
export const MARK_CONVERSATIONS_AS_READ = "MARK_CONVERSATIONS_AS_READ";
export const MARK_CONVERSATIONS_AS_UNFLAGGED = "MARK_CONVERSATIONS_AS_UNFLAGGED";
export const MARK_CONVERSATIONS_AS_UNREAD = "MARK_CONVERSATIONS_AS_UNREAD";
export const MOVE_CONVERSATION_MESSAGES = "MOVE_CONVERSATION_MESSAGES";
export const MOVE_CONVERSATIONS = "MOVE_CONVERSATIONS";
export const REMOVE_CONVERSATION_MESSAGES = "REMOVE_CONVERSATION_MESSAGES";
export const REMOVE_CONVERSATIONS = "REMOVE_CONVERSATIONS";
export const REPLACE_DRAFT_MESSAGE = "REPLACE_DRAFT_MESSAGE";

// folderList
export const RESET_FILTER = "RESET_FILTER";
export const SHOW_MORE_FOR_MAILSHARES = "SHOW_MORE_FOR_MAILSHARES";
export const SHOW_MORE_FOR_USERS = "SHOW_MORE_FOR_USERS";
