//root
export const ALL_SELECTED_MESSAGES_ARE_UNREAD = "ALL_SELECTED_MESSAGES_ARE_UNREAD";
export const ALL_SELECTED_MESSAGES_ARE_READ = "ALL_SELECTED_MESSAGES_ARE_READ";
export const ALL_SELECTED_MESSAGES_ARE_FLAGGED = "ALL_SELECTED_MESSAGES_ARE_FLAGGED";
export const ALL_SELECTED_MESSAGES_ARE_UNFLAGGED = "ALL_SELECTED_MESSAGES_ARE_UNFLAGGED";
export const ALL_MESSAGES_ARE_SELECTED = "ALL_MESSAGES_ARE_SELECTED";

export const IS_MESSAGE_LOADED = "isLoaded";
// selection
export const IS_SELECTION_EMPTY = "IS_SELECTION_EMPTY";
export const ONE_MESSAGE_SELECTED = "ONE_MESSAGE_SELECTED";
export const MULTIPLE_MESSAGE_SELECTED = "MULTIPLE_MESSAGE_SELECTED";
export const IS_MESSAGE_SELECTED = "IS_MESSAGE_SELECTED";
