// root
export const ACTIVE_MESSAGE = "ACTIVE_MESSAGE";
export const ALL_MESSAGES_ARE_SELECTED = "ALL_MESSAGES_ARE_SELECTED";
export const ALL_SELECTED_MESSAGES_ARE_FLAGGED = "ALL_SELECTED_MESSAGES_ARE_FLAGGED";
export const ALL_SELECTED_MESSAGES_ARE_READ = "ALL_SELECTED_MESSAGES_ARE_READ";
export const ALL_SELECTED_MESSAGES_ARE_UNFLAGGED = "ALL_SELECTED_MESSAGES_ARE_UNFLAGGED";
export const ALL_SELECTED_MESSAGES_ARE_UNREAD = "ALL_SELECTED_MESSAGES_ARE_UNREAD";
export const CURRENT_MAILBOX = "CURRENT_MAILBOX";
export const IS_ACTIVE_MESSAGE = "IS_ACTIVE_MESSAGE";
export const MAILSHARE_FOLDERS = "MAILSHARE_FOLDERS";
export const MAILSHARE_ROOT_FOLDERS = "MAILSHARE_ROOT_FOLDERS";
export const MAILSHARES_ARE_READY = "MAILSHARES_ARE_READY";
export const MY_DRAFTS = "MY_DRAFTS";
export const MY_INBOX = "MY_INBOX";
export const MY_MAILBOX_FOLDERS = "MY_MAILBOX_FOLDERS";
export const MY_MAILBOX_IS_READY = "MY_MAILBOX_IS_READY";
export const MY_MAILBOX_ROOT_FOLDERS = "MY_MAILBOX_ROOT_FOLDERS";
export const MY_OUTBOX = "MY_OUTBOX";
export const MY_SENT = "MY_SENT";
export const MY_TRASH = "MY_TRASH";
export const NEXT_MESSAGE = "NEXT_MESSAGE";

// mailboxes
export const MAILBOX_BY_NAME = "MAILBOX_BY_NAME";
export const MAILBOXES_ARE_LOADED = "MAILBOXES_ARE_LOADED";
export const MAILSHARE_KEYS = "MAILSHARE_KEYS";
export const MAILSHARES = "MAILSHARES";
export const MY_MAILBOX = "MY_MAILBOX";
export const MY_MAILBOX_KEY = "MY_MAILBOX_KEY";

// folders
export const IS_DESCENDANT = "IS_DESCENDANT";
export const FOLDERS_BY_UPPERCASE_PATH = "FOLDERS_BY_UPPERCASE_PATH";
export const FOLDER_HAS_CHILDREN = "FOLDER_HAS_CHILDREN";
export const FOLDER_GET_CHILDREN = "FOLDER_GET_CHILDREN";

// messages
export const MESSAGE_IS_LOADED = "MESSAGE_IS_LOADED";
export const MESSAGE_IS_LOADING = "MESSAGE_IS_LOADING";

// selection
export const SELECTION_IS_EMPTY = "SELECTION_IS_EMPTY";
export const ONE_MESSAGE_SELECTED = "ONE_MESSAGE_SELECTED";
export const MULTIPLE_MESSAGE_SELECTED = "MULTIPLE_MESSAGE_SELECTED";
export const MESSAGE_IS_SELECTED = "MESSAGE_IS_SELECTED";

// messageList
export const MESSAGE_LIST_IS_LOADING = "MESSAGE_LIST_IS_LOADING";
export const MESSAGE_LIST_IS_RESOLVED = "MESSAGE_LIST_IS_RESOLVED";
export const MESSAGE_LIST_IS_REJECTED = "MESSAGE_LIST_IS_REJECTED";
export const MESSAGE_LIST_COUNT = "MESSAGE_LIST_COUNT";
export const MESSAGE_LIST_FILTERED = "MESSAGE_LIST_FILTERED";
export const MESSAGE_LIST_UNREAD_FILTER_ENABLED = "MESSAGE_LIST_UNREAD_FILTER_ENABLED";
export const MESSAGE_LIST_FLAGGED_FILTER_ENABLED = "MESSAGE_LIST_FLAGGED_FILTER_ENABLED";

// search
export const MESSAGE_LIST_IS_SEARCH_MODE = "MESSAGE_LIST_IS_SEARCH_MODE";
