// popup
export const IS_POPUP = "IS_POPUP";

// activeMessage
export const RESET_ACTIVE_MESSAGE = "RESET_ACTIVE_MESSAGE";
export const SET_ACTIVE_MESSAGE = "SET_ACTIVE_MESSAGE";

// partsData
export const RESET_PARTS_DATA = "RESET_PARTS_DATA";
export const SET_PART_DATA = "SET_PART_DATA";
export const SET_QUOTE_NODES = "SET_QUOTE_NODES";

// mailboxes
export const ADD_MAILBOXES = "ADD_MAILBOXES";

// folders
export const ADD_FOLDER = "ADD_FOLDER";
export const REMOVE_FOLDER = "REMOVE_FOLDER";
export const SET_ACTIVE_FOLDER = "SET_ACTIVE_FOLDER";
export const SET_UNREAD_COUNT = "SET_UNREAD_COUNT";
export const SET_FOLDER_EXPANDED = "SET_FOLDER_EXPANDED";
export const UPDATE_FOLDER = "UPDATE_FOLDER";
export const UPDATE_PATHS = "UPDATE_PATHS";

// message
export const ADD_ATTACHMENT = "ADD_ATTACHMENT";
export const ADD_FLAG = "ADD_FLAG";
export const ADD_MESSAGES = "ADD_MESSAGES";
export const DELETE_FLAG = "DELETE_FLAG";
export const MOVE_MESSAGES = "MOVE_MESSAGES";
export const REMOVE_ATTACHMENT = "REMOVE_ATTACHMENT";
export const REMOVE_MESSAGES = "REMOVE_MESSAGES";
export const SET_ATTACHMENT_ADDRESS = "SET_ATTACHMENT_ADDRESS";
export const SET_ATTACHMENT_ENCODING = "SET_ATTACHMENT_ENCODING";
export const SET_ATTACHMENT_HEADERS = "SET_ATTACHMENT_HEADERS";
export const SET_ATTACHMENT_PROGRESS = "SET_ATTACHMENT_PROGRESS";
export const SET_ATTACHMENT_STATUS = "SET_ATTACHMENT_STATUS";
export const SET_ATTACHMENTS = "SET_ATTACHMENTS";
export const SET_MESSAGE_BCC = "SET_MESSAGE_BCC";
export const SET_MESSAGE_CC = "SET_MESSAGE_CC";
export const SET_MESSAGE_COMPOSING = "SET_MESSAGE_COMPOSING";
export const SET_MESSAGE_DATE = "SET_MESSAGE_DATE";
export const SET_MESSAGE_FROM = "SET_MESSAGE_FROM";
export const SET_MESSAGE_HAS_ATTACHMENT = "SET_MESSAGE_HAS_ATTACHMENT";
export const SET_MESSAGE_HEADERS = "SET_MESSAGE_HEADERS";
export const SET_MESSAGE_INTERNAL_ID = "SET_MESSAGE_INTERNAL_ID";
export const SET_MESSAGE_INLINE_PARTS_BY_CAPABILITIES = "SET_MESSAGE_INLINE_PARTS_BY_CAPABILITIES";
export const SET_MESSAGE_IMAP_UID = "SET_MESSAGE_IMAP_UID";
export const SET_MESSAGES_LOADING_STATUS = "SET_MESSAGES_LOADING_STATUS";
export const SET_MESSAGE_PREVIEW = "SET_MESSAGE_PREVIEW";
export const SET_MESSAGE_SIZE = "SET_MESSAGE_SIZE";
export const SET_MESSAGES_STATUS = "SET_MESSAGES_STATUS";
export const SET_MESSAGE_SUBJECT = "SET_MESSAGE_SUBJECT";
export const SET_MESSAGE_TMP_ADDRESSES = "SET_MESSAGE_TMP_ADDRESSES";
export const SET_MESSAGE_TO = "SET_MESSAGE_TO";

//conversationList
export const RESET_CONVERSATION_LIST_PAGE = "RESET_CONVERSATION_LIST_PAGE";
export const SET_CONVERSATION_LIST = "SET_CONVERSATION_LIST";
export const SET_CONVERSATION_LIST_FILTER = "SET_CONVERSATION_LIST_FILTER";
export const SET_CONVERSATION_LIST_STATUS = "SET_CONVERSATION_LIST_STATUS";
export const SET_CONVERSATION_LIST_PAGE = "SET_CONVERSATION_LIST_PAGE";

//search
export const SET_SEARCH_FOLDER = "SET_SEARCH_FOLDER";
export const SET_SEARCH_PATTERN = "SET_SEARCH_PATTERN";

// messageCompose
export const MAX_MESSAGE_SIZE_EXCEEDED = "MAX_MESSAGE_SIZE_EXCEEDED";
export const RESET_COMPOSER = "RESET_COMPOSER";
export const SET_CORPORATE_SIGNATURE = "SET_CORPORATE_SIGNATURE";
export const SET_PERSONAL_SIGNATURE = "SET_PERSONAL_SIGNATURE";
export const SET_DISCLAIMER = "SET_DISCLAIMER";
export const SET_DRAFT_COLLAPSED_CONTENT = "SET_DRAFT_COLLAPSED_CONTENT";
export const SET_DRAFT_EDITOR_CONTENT = "SET_DRAFT_EDITOR_CONTENT";
export const SET_MAX_MESSAGE_SIZE = "SET_MAX_MESSAGE_SIZE";
export const SET_SAVED_INLINE_IMAGES = "SET_SAVED_INLINE_IMAGES";
export const SET_TEMPLATE_CHOOSER_TARGET = "SET_TEMPLATE_CHOOSER_TARGET";
export const SET_TEMPLATE_CHOOSER_VISIBLE = "SET_TEMPLATE_CHOOSER_VISIBLE";
export const SET_TEMPLATE_LIST_LOADING = "SET_TEMPLATE_LIST_LOADING";
export const SET_TEMPLATE_LIST_SEARCH_PATTERN = "SET_TEMPLATE_LIST_SEARCH_PATTERN";
export const SET_TEMPLATES_LIST = "SET_TEMPLATES_LIST";
export const SHOW_SENDER = "SHOW_SENDER";
export const UNSET_CORPORATE_SIGNATURE = "UNSET_CORPORATE_SIGNATURE";

// selection
export const UNSELECT_CONVERSATION = "UNSELECT_CONVERSATION";
export const SELECT_CONVERSATION = "SELECT_CONVERSATION";
export const SET_SELECTION = "SET_SELECTION";
export const UNSELECT_ALL_CONVERSATIONS = "UNSELECT_ALL_CONVERSATIONS";

// consultPanel
export const SET_BLOCK_REMOTE_IMAGES = "SET_BLOCK_REMOTE_IMAGES";
export const SET_CURRENT_EVENT = "SET_CURRENT_EVENT";
export const SET_CURRENT_EVENT_STATUS = "SET_CURRENT_EVENT_STATUS";

// folderList
export const RESET_FOLDER_FILTER_LIMITS = "RESET_FOLDER_FILTER_LIMITS";
export const SET_FOLDER_FILTER_PATTERN = "SET_FOLDER_FILTER_PATTERN";
export const SET_FOLDER_FILTER_RESULTS = "SET_FOLDER_FILTER_RESULTS";
export const SET_FOLDER_FILTER_LIMIT = "SET_FOLDER_FILTER_LIMIT";
export const SET_FOLDER_FILTER_LOADED = "SET_FOLDER_FILTER_LOADED";
export const SET_FOLDER_FILTER_LOADING = "SET_FOLDER_FILTER_LOADING";
export const TOGGLE_EDIT_FOLDER = "TOGGLE_EDIT_FOLDER";

// route
export const SET_ROUTE_FILTER = "SET_ROUTE_FILTER";
export const SET_ROUTE_FOLDER = "SET_ROUTE_FOLDER";
export const SET_ROUTE_MAILBOX = "SET_ROUTE_MAILBOX";
export const SET_ROUTE_SEARCH = "SET_ROUTE_SEARCH";

// conversations
export const ADD_CONVERSATIONS = "ADD_CONVERSATIONS";
export const REMOVE_CONVERSATIONS = "REMOVE_CONVERSATIONS";
export const RESET_CONVERSATIONS = "RESET_CONVERSATIONS";
export const SET_CONVERSATIONS_LOADING_STATUS = "SET_CONVERSATIONS_LOADING_STATUS";
export const SET_CURRENT_CONVERSATION = "SET_CURRENT_CONVERSATION";
export const UNSET_CURRENT_CONVERSATION = "UNSET_CURRENT_CONVERSATION";

// settings
export const SET_MAIL_THREAD_SETTING = "SET_MAIL_THREAD_SETTING";

// preview
export const SET_PREVIEW_PART_ADDRESS = "SET_PREVIEW_PART_ADDRESS";
export const SET_PREVIEW_MESSAGE_KEY = "SET_PREVIEW_MESSAGE_KEY";
