// message
export const ADD_ATTACHMENT = "ADD_ATTACHMENT";
export const ADD_FLAG = "ADD_FLAG";
export const ADD_MESSAGES = "ADD_MESSAGES";
export const DELETE_FLAG = "DELETE_FLAG";
export const REMOVE_ATTACHMENT = "REMOVE_ATTACHMENT";
export const REMOVE_MESSAGE_PART_CONTENTS = "REMOVE_MESSAGE_PART_CONTENTS";
export const REMOVE_MESSAGES = "REMOVE_MESSAGES";
export const SET_ATTACHMENT_ADDRESS = "SET_ATTACHMENT_ADDRESS";
export const SET_ATTACHMENT_CONTENT_URL = "SET_ATTACHMENT_CONTENT_URL";
export const SET_ATTACHMENT_PROGRESS = "SET_ATTACHMENT_PROGRESS";
export const SET_ATTACHMENT_STATUS = "SET_ATTACHMENT_STATUS";
export const SET_MESSAGE_BCC = "SET_MESSAGE_BCC";
export const SET_MESSAGE_CC = "SET_MESSAGE_CC";
export const SET_MESSAGE_COMPOSING = "SET_MESSAGE_COMPOSING";
export const SET_MESSAGE_DATE = "SET_MESSAGE_DATE";
export const SET_MESSAGE_HEADERS = "SET_MESSAGE_HEADERS";
export const SET_MESSAGE_PART_CONTENTS = "SET_MESSAGE_PART_CONTENTS";
export const SET_MESSAGE_SUBJECT = "SET_MESSAGE_SUBJECT";
export const SET_MESSAGE_TO = "SET_MESSAGE_TO";
export const SET_MESSAGES_STATUS = "SET_MESSAGES_STATUS";

//messageList
export const CLEAR_MESSAGE_LIST = "CLEAR_MESSAGE_LIST";
export const SET_MESSAGE_LIST = "SET_MESSAGE_LIST";
export const SET_MESSAGE_LIST_FILTER = "SET_MESSAGE_LIST_FILTER";
export const SET_MESSAGE_LIST_STATUS = "SET_MESSAGE_LIST_STATUS";

//search
export const SET_SEARCH_FOLDER = "SET_SEARCH_FOLDER";
export const SET_SEARCH_PATTERN = "SET_SEARCH_PATTERN";

// messageCompose
export const SET_DRAFT_COLLAPSED_CONTENT = "SET_DRAFT_COLLAPSED_CONTENT";
export const SET_DRAFT_EDITOR_CONTENT = "SET_DRAFT_EDITOR_CONTENT";

// selection
export const UNSELECT_MESSAGE = "UNSELECT_MESSAGE";
export const SELECT_MESSAGE = "SELECT_MESSAGE";
export const SELECT_ALL_MESSAGES = "SELECT_ALL_MESSAGES";
export const UNSELECT_ALL_MESSAGES = "UNSELECT_ALL_MESSAGES";
