// activeMessage
export const RESET_ACTIVE_MESSAGE = "RESET_ACTIVE_MESSAGE";
export const SET_ACTIVE_FOLDER = "SET_ACTIVE_FOLDER";
export const SET_ACTIVE_MESSAGE_PART_DATA = "SET_ACTIVE_MESSAGE_PART_DATA";

// mailboxes
export const ADD_MAILBOXES = "ADD_MAILBOXES";

// folders
export const ADD_FOLDER = "ADD_FOLDER";
export const ADD_FOLDERS = "ADD_FOLDERS";
export const RENAME_FOLDER = "RENAME_FOLDER";
export const REMOVE_FOLDER = "REMOVE_FOLDER";
export const SET_UNREAD_COUNT = "SET_UNREAD_COUNT";
export const SET_FOLDER_EXPANDED = "SET_FOLDER_EXPANDED";

// message
export const ADD_ATTACHMENT = "ADD_ATTACHMENT";
export const ADD_FLAG = "ADD_FLAG";
export const ADD_MESSAGES = "ADD_MESSAGES";
export const DELETE_FLAG = "DELETE_FLAG";
export const MOVE_MESSAGES = "MOVE_MESSAGES";
export const REMOVE_ATTACHMENT = "REMOVE_ATTACHMENT";
export const REMOVE_MESSAGES = "REMOVE_MESSAGES";
export const SET_ATTACHMENT_ADDRESS = "SET_ATTACHMENT_ADDRESS";
export const SET_ATTACHMENT_ENCODING = "SET_ATTACHMENT_ENCODING";
export const SET_ATTACHMENT_PROGRESS = "SET_ATTACHMENT_PROGRESS";
export const SET_ATTACHMENT_STATUS = "SET_ATTACHMENT_STATUS";
export const SET_MESSAGE_BCC = "SET_MESSAGE_BCC";
export const SET_MESSAGE_CC = "SET_MESSAGE_CC";
export const SET_MESSAGE_COMPOSING = "SET_MESSAGE_COMPOSING";
export const SET_MESSAGE_DATE = "SET_MESSAGE_DATE";
export const SET_MESSAGE_HAS_ATTACHMENT = "SET_MESSAGE_HAS_ATTACHMENT";
export const SET_MESSAGE_HEADERS = "SET_MESSAGE_HEADERS";
export const SET_MESSAGE_INTERNAL_ID = "SET_MESSAGE_INTERNAL_ID";
export const SET_MESSAGE_INLINE_PARTS_BY_CAPABILITIES = "SET_MESSAGE_INLINE_PARTS_BY_CAPABILITIES";
export const SET_MESSAGE_IMAP_UID = "SET_MESSAGE_IMAP_UID";
export const SET_MESSAGE_PREVIEW = "SET_MESSAGE_PREVIEW";
export const SET_MESSAGES_STATUS = "SET_MESSAGES_STATUS";
export const SET_MESSAGE_SUBJECT = "SET_MESSAGE_SUBJECT";
export const SET_MESSAGE_TO = "SET_MESSAGE_TO";

//messageList
export const CLEAR_MESSAGE_LIST = "CLEAR_MESSAGE_LIST";
export const SET_MESSAGE_LIST = "SET_MESSAGE_LIST";
export const SET_MESSAGE_LIST_FILTER = "SET_MESSAGE_LIST_FILTER";
export const SET_MESSAGE_LIST_STATUS = "SET_MESSAGE_LIST_STATUS";

//search
export const SET_SEARCH_FOLDER = "SET_SEARCH_FOLDER";
export const SET_SEARCH_PATTERN = "SET_SEARCH_PATTERN";

// messageCompose
export const RESET_ATTACHMENTS_FORWARDED = "RESET_ATTACHMENTS_FORWARDED";
export const SET_ATTACHMENTS_FORWARDED = "SET_ATTACHMENTS_FORWARDED";
export const SET_DRAFT_COLLAPSED_CONTENT = "SET_DRAFT_COLLAPSED_CONTENT";
export const SET_DRAFT_EDITOR_CONTENT = "SET_DRAFT_EDITOR_CONTENT";
export const SET_SAVED_INLINE_IMAGES = "SET_SAVED_INLINE_IMAGES";
export const SET_SIGNATURE = "SET_SIGNATURE";

// selection
export const UNSELECT_MESSAGE = "UNSELECT_MESSAGE";
export const SELECT_MESSAGE = "SELECT_MESSAGE";
export const SELECT_ALL_MESSAGES = "SELECT_ALL_MESSAGES";
export const UNSELECT_ALL_MESSAGES = "UNSELECT_ALL_MESSAGES";

// consultPanel
export const SET_BLOCK_REMOTE_IMAGES = "SET_BLOCK_REMOTE_IMAGES";
export const SET_CURRENT_EVENT = "SET_CURRENT_EVENT";
export const SET_CURRENT_EVENT_STATUS = "SET_CURRENT_EVENT_STATUS";
export const SET_SHOW_REMOTE_IMAGES_ALERT = "SET_SHOW_REMOTE_IMAGES_ALERT";

// folderList
export const TOGGLE_EDIT_FOLDER = "TOGGLE_EDIT_FOLDER";

// addressbooks
export const SET_MY_CONTACTS_ADDRESSBOOK = "SET_MY_CONTACTS_ADDRESSBOOK";
