const USED_QUOTA_PERCENTAGE_WARNING = 80; // quota usage is considered as "to be watched" if it's more than 80%
const USED_QUOTA_PERCENTAGE_DANGER = 90;
const USED_QUOTA_PERCENTAGE_UNSAFE = 95;
const USED_QUOTA_PERCENTAGE_CRITICAL = 99;

export {
    USED_QUOTA_PERCENTAGE_WARNING,
    USED_QUOTA_PERCENTAGE_DANGER,
    USED_QUOTA_PERCENTAGE_UNSAFE,
    USED_QUOTA_PERCENTAGE_CRITICAL
};
