#!/bin/bash
#BEGIN LICENSE
#
# Copyright © Blue Mind SAS, 2012-2018
#
# This file is part of BlueMind. BlueMind is a messaging and collaborative
# solution.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of either the GNU Affero General Public License as
# published by the Free Software Foundation (version 3 of the License).
#
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# See LICENSE.txt


export JAVA_HOME=/usr/lib/jvm/bm-jdk

appid=net.bluemind.cli.launcher.cli

product=bm-cli
curdir=/usr/share/bm-cli

AGENT_ENABLED=0
source ${curdir}/equinox-systemd.sh ${product}

bm_equinox_run_server_appid ${curdir} ${appid} $@
