// actions
export const DISSOCIATE_CRYPTO_FILES = "DISSOCIATE_CRYPTO_FILES";
export const CHECK_IF_ASSOCIATED = "CHECK_IF_ASSOCIATED";

// getters
export const SMIME_AVAILABLE = "SMIME_AVAILABLE";

// mutations
export const SET_HAS_PRIVATE_KEY = "SET_HAS_PRIVATE_KEY";
export const SET_HAS_PUBLIC_CERT = "SET_HAS_PUBLIC_CERT";
export const SET_SW_AVAILABLE = "SET_SW_AVAILABLE";
export const SET_SW_ERROR = "SET_SW_ERROR";
