export const ADD_FH_ATTACHMENT = "ADD_FH_ATTACHMENT";
export const ADD_FH_FILE = "ADD_FH_FILE";
export const DETACH_ATTACHMENT = "DETACH_ATTACHMENT";
export const GET_CONFIGURATION = "GET_CONFIGURATION";
export const LINK_FH_ATTACHMENT = "LINK_FH_ATTACHMENT";
export const SHARE_ATTACHMENT = "SHARE_ATTACHMENT";
