// actions
export const ADD_CERTIFICATE = "ADD_CERTIFICATE";

// mutations
export const DISPLAY_UNTRUSTED = "DISPLAY_UNTRUSTED";
export const RESET_MISSING_CERTIFICATES = "RESET_MISSING_CERTIFICATES";
