export const SMIME_INTERNAL_API_URL = "/service-worker-internal/smime";
export enum PKIStatus {
    EMPTY = 0,
    CERTIFICATE_OK = 1,
    PRIVATE_KEY_OK = 2,
    OK = PRIVATE_KEY_OK | CERTIFICATE_OK
}
export enum PKIEntry {
    PRIVATE_KEY = "privateKey",
    CERTIFICATE = "certificate"
}
export const ENCRYPTED_HEADER_NAME = "X-MailApp-Encrypted";
export const SIGNED_HEADER_NAME = "X-MailApp-Signed";
export enum CRYPTO_HEADERS {
    TO_DO = 1,
    OK = 2,
    INVALID_KEY = 4,
    KEY_NOT_FOUND = 8,
    INVALID_CERTIFICATE = 16,
    MY_CERTIFICATE_NOT_FOUND = 32,
    UNSUPPORTED_ALGORITHM = 64,
    UNTRUSTED_CERTIFICATE = 128,
    UNMATCHED_CERTIFICATE = 256,
    INVALID_MESSAGE_INTEGRITY = 512,
    INVALID_PKCS7_ENVELOPE = 1024,
    INVALID_SIGNATURE = 2048,
    DECRYPT_FAILURE = 4096,
    ENCRYPT_FAILURE = 8192,
    CERTIFICATE_RECIPIENT_NOT_FOUND = 16384,
    SIGN_FAILURE = 32768,
    UNTRUSTED_CERTIFICATE_EMAIL_NOT_FOUND = 65536,
    UNKNOWN = 131072
}
export enum SMIMEPrefKeys {
    SIGNATURE = "sign_message_by_default",
    ENCRYPTION = "encrypt_message_by_default"
}
export enum SMIME_CERT_USAGE {
    SIGN = "SIGN",
    ENCRYPT = "ENCRYPT"
}
export const IS_SW_AVAILABLE = !!navigator.serviceWorker?.controller;

export const SMIME_ENCRYPTION_ERROR_PREFIX = "SMIME_ENCRYPTION_ERROR";
export const SMIME_SIGNATURE_ERROR_PREFIX = "SMIME_SIGNATURE_ERROR";
export const SMIME_UNTRUSTED_CERTIFICATE_ERROR_PREFIX = "SMIME_UNTRUSTED_CERTIFICATE_ERROR";

export const smimeErrorMsgRegex = new RegExp(
    `\\[(${SMIME_ENCRYPTION_ERROR_PREFIX}|${SMIME_SIGNATURE_ERROR_PREFIX}|${SMIME_UNTRUSTED_CERTIFICATE_ERROR_PREFIX}):(.*)\\]`
);
