<?php

/*
 +-----------------------------------------------------------------------+
 | localization/nl_NL/labels.inc                                         |
 |                                                                       |
 | Language file of the Roundcube Webmail client                         |
 | Copyright (C) 2012, The Roundcube Dev Team                            |
 | Licensed under the GNU General Public License                         |
 |                                                                       |
 +-----------------------------------------------------------------------+
 | Author: Nicolas Delvaux                                               |
 +-----------------------------------------------------------------------+
*/

$labels = array();
include INSTALL_PATH . "program/localization/nl.php";
?>
