{  
   "addons":{  
      "bm-connector-tb@blue-mind.net":{  
         "updates":[  
            {  
               "version":"${version}",
               "update_link":"${url}"
            }
         ]
      }
   }
}