<?php
/*
+-----------------------------------------------------------------------+
| language/fr/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Anthony Prades <toony.github@chezouam.net>                    |
+-----------------------------------------------------------------------+
*/

$labels = array();
include INSTALL_PATH . "plugins/compose_newwindow/localization/fr.php";

?>
