<?php
/**
 * compose_newwindow - Compose(Reply/Forward) in a New Window
 *
 * @version 3.00 (20110822)
 * @author Karl McMurdo (user xrxca on roundcubeforum.net)
 * @url http://github.com/xrxca/cnw
 * @copyright (c) 2010-2011 Karl McMurdo
 *
 */
$labels = array();

$labels['compose_newwindow'] = 'Redactar nunha fiestra nova';
$labels['enabled'] = 'Activar a redacción nunha fiestra nova';
$labels['hidebar'] = 'Ocultar a barra de ferramentas nas fiestras de redacción';
?>
