<?php

/*
+-----------------------------------------------------------------------+
| language/it_IT/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['compose_newwindow'] = 'Componi in Nuova Finestra';
$labels['enabled'] = 'Abilita composizione in nuova finestra';
$labels['hidebar'] = 'Nascondi toolbar principale in componi finestre';


include INSTALL_PATH . "plugins/compose_newwindow/localization/it.php";
?>