<?php

/*
+-----------------------------------------------------------------------+
| language/nl_NL/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author:                                                               |
+-----------------------------------------------------------------------+

*/

$labels = array();

$labels['compose_newwindow'] = 'Berichten in Nieuw Venster';
$labels['enabled'] = 'Nieuw bericht maken in een nieuw venster';
$labels['hidebar'] = 'Werkbalk verbergen in nieuw bericht-venster';


include INSTALL_PATH . "plugins/compose_newwindow/localization/nl.php";
?>