<?php

/*
+-----------------------------------------------------------------------+
| language/pt_BR/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: trturino                                                      |
+-----------------------------------------------------------------------+

*/

$labels = array();
$labels['compose_newwindow'] = 'Escrever em nova janela';
$labels['enabled'] = 'Ativar escrever em nova janela';
$labels['hidebar'] = 'Esconder barra de ferramentas principal na janela de novo email';

?>