<?php

/*
+-----------------------------------------------------------------------+
| language/ru_RU/labels.inc                                             |
|                                                                       |
| Language file of the RoundCube Webmail client                         |
| Copyright (C) 2008-2009, RoundQube Dev. - Switzerland                 |
| Licensed under the GNU GPL                                            |
|                                                                       |
+-----------------------------------------------------------------------+
| Author: Peter Zotov <whitequark@whitequark.org>                       |
+-----------------------------------------------------------------------+

*/

$labels = array();

$labels['compose_newwindow'] = 'Написать сообщение в новом окне';
$labels['enabled'] = 'Составлять сообщения в новом окне';
$labels['hidebar'] = 'Скрывать панель инструментов в окнах составления сообщения';

include INSTALL_PATH . "plugins/compose_newwindow/localization/ru.php";
?>