export default {
    // messages
    FETCH_MESSAGE_METADATA: "FETCH_MESSAGE_METADATA",
    REMOVE_MESSAGES: "REMOVE_MESSAGES",
    ADD_FLAG: "ADD_FLAG",
    DELETE_FLAG: "DELETE_FLAG",
    ADD_ATTACHMENTS: "ADD_ATTACHMENTS",
    REMOVE_ATTACHMENT: "REMOVE_ATTACHMENT",
    SAVE_MESSAGE: "SAVE_MESSAGE",
    SEND_MESSAGE: "SEND_MESSAGE",

    // message list
    FETCH_FOLDER_MESSAGE_KEYS: "FETCH_FOLDER_MESSAGE_KEYS"
};
