export default {
    // messages
    FETCH_MESSAGE_METADATA: "FETCH_MESSAGE_METADATA",
    REMOVE_MESSAGES: "REMOVE_MESSAGES",
    ADD_FLAG: "ADD_FLAG",
    DELETE_FLAG: "DELETE_FLAG",
    // message list
    FETCH_FOLDER_MESSAGE_KEYS: "FETCH_FOLDER_MESSAGE_KEYS"
};
