export default {
    //messages
    ADD_FLAG: "ADD_FLAG",
    DELETE_FLAG: "DELETE_FLAG",
    ADD_MESSAGES: "ADD_MESSAGES",
    REMOVE_MESSAGES: "REMOVE_MESSAGES",
    SET_MESSAGES_STATUS: "SET_MESSAGES_STATUS",
    //message list
    SET_MESSAGE_LIST: "SET_MESSAGE_LIST",
    CLEAR_MESSAGE_LIST: "CLEAR_MESSAGE_LIST"
};
