export default {
    //messages
    ADD_FLAG: "ADD_FLAG",
    DELETE_FLAG: "DELETE_FLAG",
    ADD_MESSAGES: "ADD_MESSAGES",
    REMOVE_MESSAGES: "REMOVE_MESSAGES",
    SET_MESSAGES_STATUS: "SET_MESSAGES_STATUS",
    SET_MESSAGE_COMPOSING: "SET_MESSAGE_COMPOSING",
    SET_MESSAGE_SUBJECT: "SET_MESSAGE_SUBJECT",
    SET_MESSAGE_RECIPIENTS: "SET_MESSAGE_RECIPIENTS",
    SET_MESSAGE_DATE: "SET_MESSAGE_DATE",
    ADD_ATTACHMENT: "ADD_ATTACHMENT",
    REMOVE_ATTACHMENT: "REMOVE_ATTACHMENT",
    UPDATE_ATTACHMENT: "UPDATE_ATTACHMENT",
    SET_ATTACHMENT_STATUS: "SET_ATTACHMENT_STATUS",
    SET_ATTACHMENT_PROGRESS: "SET_ATTACHMENT_PROGRESS",
    SET_ATTACHMENT_CONTENT_URL: "SET_ATTACHMENT_CONTENT_URL",
    SET_MESSAGE_HEADERS: "SET_MESSAGE_HEADERS",
    SET_MESSAGE_ATTACHMENTS: "SET_MESSAGE_ATTACHMENTS",

    //message list
    SET_MESSAGE_LIST: "SET_MESSAGE_LIST",
    CLEAR_MESSAGE_LIST: "CLEAR_MESSAGE_LIST",
    SET_MESSAGE_LIST_STATUS: "SET_MESSAGE_LIST_STATUS",
    SET_MESSAGE_LIST_FILTER: "SET_MESSAGE_LIST_FILTER",

    // messageCompose
    SET_DRAFT_EDITOR_CONTENT: "SET_DRAFT_EDITOR_CONTENT",
    SET_DRAFT_COLLAPSED_CONTENT: "SET_DRAFT_COLLAPSED_CONTENT"
};
