#!/bin/bash
#BEGIN LICENSE
#
# Copyright © Blue Mind SAS, 2012-2019
#
# This file is part of BlueMind. BlueMind is a messaging and collaborative
# solution.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of either the GNU Affero General Public License as
# published by the Free Software Foundation (version 3 of the License).
#
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# See LICENSE.txt


appid=net.bluemind.sds.proxy.launcher.sds-proxy

product=`basename $0`
curdir=`dirname $0`

export DEFAULT_MEM=128

export BM_JVM_CUSTOM_OPTS="-Dio.netty.allocator.maxOrder=8"


source ${curdir}/equinox-systemd.sh ${product}

case "$1" in
    "pre-start")
        bm_pre_start bluemind
        ;;
    "post-start")
        bm_post_start bluemind
        ;;
    *)
        bm_equinox_run_server_appid ${curdir} ${appid} $@
        ;;
esac
