#!/bin/bash
#BEGIN LICENSE
#
# Copyright © Blue Mind SAS, 2012-2016
#
# This file is part of BlueMind. BlueMind is a messaging and collaborative
# solution.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of either the GNU Affero General Public License as
# published by the Free Software Foundation (version 3 of the License).
#
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# See LICENSE.txt


appid=net.bluemind.tika.server.tika

product=`basename $0`
curdir=`dirname $0`
pidfile=$1

export DEFAULT_MEM=128
export OOM="-XX:OnOutOfMemoryError=/usr/share/bm-tika/bin/oom_kill.sh"

source ${curdir}/equinox-systemd.lib ${product}

# they are created on start by tika java code
rm -fr /var/spool/bm-tika/work/
rm -fr /var/spool/bm-tika/cache/

bm_equinox_run_server_appid ${curdir} ${appid}
